services:
  - type: web
    name: collapsi
    env: docker
    rootDir: .
    plan: free
    autoDeploy: true
    dockerfilePath: Collapsi/Dockerfile
    healthCheckPath: /
    envVars:
      - key: COLLAPSI_DB
        value: /opt/render/project/src/data/collapsi.db
    disk:
      name: collapsi-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1


