services:
  - type: web
    name: collapsi
    env: docker
    rootDir: .
    plan: free
    autoDeploy: true
    dockerfilePath: Collapsi/Dockerfile
    healthCheckPath: /
    envVars:
      - key: COLLAPSI_DB
        value: /tmp/collapsi.db