services:
  - type: web
    name: collapsi
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: COLLAPSI_DB
        value: /opt/render/project/src/data/collapsi.db
    disks:
      - name: collapsi-data
        mountPath: /opt/render/project/src/data
        sizeGB: 1


